### ISSUE TITLE
OrangePi Prima HDMI display doesn't work

### ISSUE THREAD

**Issue by nouatzi** [orangepi-xunlong/OrangePi_Build#10]
I have built for OrangePi Prima, and the compilation went OK. However, on boot, I have nothing displayed on a HDMI screen. If I download the pre-built image from [orangepi.org](http://www.orangepi.org/downloadresources/), the HDMI display works.
Where in the github code to change the display settings for HDMI ? u-boot ? kernel ? kernel drivers ? kernel arguments (uEnv.txt) ?

**Comment by Jeepgoing** [comment]
hello, dou you have solve this issue? @nouatzi

**Comment by orangepi-xunlong** [comment]
Hi, the problem has been solved in the latest code.
