### ISSUE TITLE
Mainline uboot repository not found

### ISSUE THREAD

**Issue by Meach** [orangepi-xunlong/OrangePi_Build#102]
When building for Zero Plus 2 (H3) and select Kernel 5.3.5, it tries to download the mainline uboot repository from [https://github.com/orangepi-xunlong/mainline_uboot](https://github.com/orangepi-xunlong/mainline_uboot)
But this repository doesn't exist.

**Comment by orangepi-xunlong** [comment]
Please use this latest code：https://github.com/orangepi-xunlong/orangepi-build
The U-boot code is here：https://github.com/orangepi-xunlong/u-boot-orangepi.git
