### ISSUE TITLE
OPi R1 Not in the supported list yet

### ISSUE THREAD

**Issue by roizpi** [orangepi-xunlong/OrangePi_Build#13]
Hi, it's been some time since the repository is not updated, and the variant of OPi Zero known as Opi R1, has been released in the mean time, and is not in the supported list yet. Any news regarding the compilation of the Linux Kernel for the R1 model?

Thank you,
Kind regards.

**Comment by ITwrx** [comment]
i'm interested in this as well.

**Comment by orangepi-xunlong** [comment]
We have updated the compilation system of H2+, Orange Pi R1 is now supported, welcome to use it.
Supported build environment is Ubuntu Bionic 18.04 x64.
