### ISSUE TITLE
Step 2 not working !!

### ISSUE THREAD

**Issue by vincegre** [orangepi-xunlong/OrangePi_Build#18]
Hi

As you don't supply an image with at least basic drivers for Pi One Plus, I tried to compile it myself but at step 2 when I run the Build_OrangePi.sh script it asks me for my root password and that's it, it returns to prompt without any errors but doing nothing !!
Fedora 27 (host system on which I try to build the image !)

Thanks

Vincèn

**Comment by EvilOlaf** [comment]
Add your user account to sudoers and provided your users password when asked.

**Comment by vincegre** [comment]
> Add your user account to sudoers and provided your users password when asked.

Sorry but my account is already in sudoers and I supplied the correct password !  Any other ideas ? trying to compile on Fedora is not going to be a problem ? on I should do that from an Ubuntu host ?

**Comment by EvilOlaf** [comment]
As I successfully ran the scripts successfully on Ubuntu server 16.04 amd64 (except a small issue for which I provided a fix https://github.com/orangepi-xunlong/OrangePiH6_scripts/pull/1) I'd recommend yes. Retry using an Ubuntu (based) OS.

**Comment by vincegre** [comment]
@EvilOlaf thanks but I gave up considering how manufacturer itself don't care at all about it :(

**Comment by EvilOlaf** [comment]
That's the price for low cost hardware I guess g ¯\_(ツ)_/¯

**Comment by vincegre** [comment]
> That's the price for low cost hardware I guess ¯\(ツ)/¯
Well you can do some cheap hardware and still good software (but well chinese companies are most of time famous for their so poor softwares/firmwares unless hardware is really nice sometimes.....
