### ISSUE TITLE
broken toolchain

### ISSUE THREAD

**Issue by leiche5** [orangepi-xunlong/OrangePi_Build#2]
i downloaded stuff and ran Build_OrangePi.sh which has worked. after changing dir to OrangePiRDA and ran build.sh, script stops because the toolchain folder is empty.

**Comment by JustTheTwoOfUs** [comment]
you may just be missing curl, sudo apt-get install curl.
re run the first Build "Build orange pi" and try updating

**Comment by harnnless** [comment]
New installation of Ubuntu Server 16.04.3, missing unzip.  sudo apt-get install unzip

**Comment by warhawk-avg** [comment]
Enter the directory where the OPi2G build is located...then git clone into the toolchain provided on main build page.
Delete the old toolchain directory
rename the newly cloned directory to directory
That's how I got mine working

**Comment by orangepi-xunlong** [comment]
You can refer to #24.

Thanks!
