### ISSUE TITLE
OPi Win+ Toolchain issue

### ISSUE THREAD

**Issue by silentbogo** [orangepi-xunlong/OrangePi_Build#23]
Trying to build a distro for OrangePi Win Plus...
I'm getting an error, regarding unpacking of the toolchain archive (toolchain.tar.gz)
First error was due to the wrong location of the archive in the build script (OrangePiA64/toolchain/ instead of OrangePiA64/toolchain/toolchain_tar/)
After moving the tarball to that location I've got this error:
![capture](https://user-images.githubusercontent.com/7000839/40628813-e60e0d5a-62cf-11e8-8667-31f0d434220f.PNG)

Only a moment later I noticed that the file size was only zero bytes....

EDIT: just a few minutes later I've manually downloaded a toolchain for Win+ and moved all files to toolchain_tar folder. The unpacking process went though and I was able to start compiling the image.

**Comment by EvilOlaf** [comment]
Probably known issue.
Make sure `curl` is installed.

**Comment by silentbogo** [comment]
Yep, curl is installed. All other components get downloaded no problem. 
Afterwards (after manually creating folder and copying toolchain), everything seems to work and compile just fine.
I'll look into scripts later tonight and try to figure out why the toolchain isn't downloading.

**Comment by warhawk-avg** [comment]
Enter the directory where the OPi2G build is located...then git clone into the toolchain provided on main build page.
Delete the old toolchain directory
rename the newly cloned directory to directory
That's how I got mine working

**Comment by orangepi-xunlong** [comment]
Has been updated.
