### ISSUE TITLE
Fails to install toolchain for H5

### ISSUE THREAD

**Issue by ril3y** [orangepi-xunlong/OrangePi_Build#24]
After running ./build.sh
```
/home/ril3y/dev/OrangePiH5
 Uncompress toolchain..
cat: '/home/ril3y/dev/OrangePiH5/toolchain/toolchain_tar/toolchain*': No such file or directory
```

Not sure what the error is.

**Comment by ril3y** [comment]
nothing?

**Comment by Jeepgoing** [comment]
make sure `curl` is installed.

**Comment by warhawk-avg** [comment]
I had to manually git clone the toolchain into the directory..then move/rename the OrangePiH5_toolchain to just plain toolchain to get it to compile
cd /home/ril3y/dev/OrangePiH5
git clone https://github.com/orangepi-xunlong/OrangePiH5_toolchain.git
sudo rm -rf toolchain
sudo mv OrangePiH5_toolchain toolchain

Make sure you have run the OrangePi_Build/lib/PrepareTool.sh to install the required dependencies for the build

**Comment by abo-github** [comment]
Okay ... that's wired - but now it works!

I really had to git clone the repo **OrangePi_Build** with
`
git clone https://github.com/orangepi-xunlong/OrangePi_Build.git
`
Downloading the zip file and extracting it didn't work for me.

So you have to follow exactly the instructions on
[https://github.com/orangepi-xunlong/OrangePi_Build](url)

**Comment by orangepi-xunlong** [comment]
The lack of access to the toolchain is due to a network problem that caused the download to fail. You may be able to try to re-download the code through the OrangePi_Build. A separate download for OrangePiH5_toolchain.git is not recommended. 

Thanks!
