### ISSUE TITLE
No option for build OrangePi zero plus 2 H5

### ISSUE THREAD

**Issue by allerallegro** [orangepi-xunlong/OrangePi_Build#3]
There is no option to build the image for the OrangePi Zero Plus 2 H5 model.
![capturar](https://user-images.githubusercontent.com/31351604/29720752-44a38160-8991-11e7-8209-780a62da92d8.PNG)

**Comment by roizpi** [comment]
@allerallegro How did you manage to build it for OrangePi Zero Plus 2 H5 model?
