### ISSUE TITLE
/bin/sleep

### ISSUE THREAD

**Issue by webstersx01** [orangepi-xunlong/OrangePi_Build#30]
Building on ubuntu 18.04(16.04 too) x64, this error:
DEBOOTSTRAP, SECOND-STAGE

please wait \/second-stage: line 206: /bin/sleep: cannot execute binary file: Exec format error
please wait |/second-stage: line 206: /bin/sleep: cannot execute binary file: Exec format error
please wait //second-stage: line 206: /bin/sleep: cannot execute binary file: Exec format error
please wait -/second-stage: line 206: /bin/sleep: cannot execute binary file: Exec format error
please wait \/second-stage: line 206: /bin/sleep: cannot execute binary file: Exec format error
please wait |/debootstrap/debootstrap: line 382: /bin/cat: cannot execute binary file: Exec format error
/second-stage: line 206: /bin/sleep: cannot execute binary file: Exec format error
ERROR.                     
================================================
ERROR on second-stage, instalation NOT FINISHED.
================================================

**Comment by sabur2342** [comment]
Programs that must be installed before the assembly of OS^
apt-get install curl libcurl4 libcurl4-openssl-dev
apt-get install lib32stdc++6
apt-get install git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc
apt-get install linux-source
apt-get install debootstrap
apt-get install schroot
apt-get install binfmt-support qemu qemu-user-static
apt-get install lib32ncurses5 lib32ncurses5-dev libusb-1.0-0-dev

**Comment by webstersx01** [comment]
Okay, now I can compile ubuntu/debian, but on raspbian compilation I have another trouble: Error while loading /bin/bash: No such file or directory

**Comment by webstersx01** [comment]
Thank you very much!
