### ISSUE TITLE
Keyboard not available with Kernel 3.4 for OrangePi PC

### ISSUE THREAD

**Issue by human890209** [orangepi-xunlong/OrangePi_Build#37]
Hi,
I build a Raspbian Jessie and an Ubuntu Xenial for my OrangePi PC with Kernal 3.40.
When my Opi boots up to the OrangePi login page.
The keyboard is not available. Can't type anything. And I pressed NumLock, the LED didn't light up.

**Comment by orangepi-xunlong** [comment]
You can try the latest image and code, I'm sorry for the trouble, thank you.
