### ISSUE TITLE
Error building OrangePi zero plus2 b5

### ISSUE THREAD

**Issue by allerallegro** [orangepi-xunlong/OrangePi_Build#4]
fsbuild: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
cp: cannot stat 'boot-resource.fex': No such file or directory
pack boot package
GetPrivateProfileSection read to end
content_count=3
file /home/aller/Downloads/OrangePiH5/output/pack/out/u-boot.fex cant be open
create package failed
ERROR: dragonsecboot  boot_package.cfg failed

**Comment by ewoutp** [comment]
same here (for Orange PI PC2)

**Comment by ewoutp** [comment]
Solved it by running this on my ubuntu build machine:
```
sudo apt-get install lib32stdc++6
```
