### ISSUE TITLE
Request Mali OpengGL Support

### ISSUE THREAD

**Issue by Jeepgoing** [orangepi-xunlong/OrangePi_Build#41]
do we have mali opengl support plan? i have been testing mali opengl for weeks, but i have not success until now, so i think maybe found some help from here, thanks.

**Comment by SonicNorg** [comment]
No graphic acceleration on Ubuntu Orange Pi 3.

**Comment by LeoAtreides** [comment]
https://github.com/jernejsk/H6-mali-userspace/issues/1

will this do it
