### ISSUE TITLE
./H6SDK_Linux4_9_BuildEnvironment.sh: line 15: Linux4.9_GITHUB=https://github.com/orangepi-xunlong/OrangePiH6_Linux4.9.git: No such file or directory

### ISSUE THREAD

**Issue by krachlatte** [orangepi-xunlong/OrangePi_Build#47]
+ '[' -z ']'
++ cd ..
++ pwd
+ TOP_ROOT=/home/krachlatte/buildstuff/OrangePi_Build
+ Linux4.9_GITHUB=https://github.com/orangepi-xunlong/OrangePiH6_Linux4.9.git
./H6SDK_Linux4_9_BuildEnvironment.sh: line 15: Linux4.9_GITHUB=https://github.com/orangepi-xunlong/OrangePiH6_Linux4.9.git: No such file or directory

this happens when tring to setup the build env for orangepi 3 and orangepi one plus for 4.9 kernel

**Comment by paszkoski** [comment]
That's because they set a variable name as Linux4.9_GITHUB and bash variables are not allowed to have "." in the name.

**Comment by alenon** [comment]
resolved here #
