### ISSUE TITLE
chroot problem

### ISSUE THREAD

**Issue by war2973** [orangepi-xunlong/OrangePi_Build#5]
Hi all,

I cannot build OrangePi Zero Plus2 (H5) image for Ubuntu Xenial:

+ chroot /home/war/OrangePi/OrangePiH5/output/rootfs mount -t proc proc /proc
chroot: failed to run command ‘mount’: Exec format error
+ true
+ chroot /home/war/OrangePi/OrangePiH5/output/rootfs mount -t sysfs sys /sys
chroot: failed to run command ‘mount’: Exec format error
+ true
+ chroot /home/war/OrangePi/OrangePiH5/output/rootfs /second-phase
chroot: failed to run command ‘/second-phase’: Exec format error

any idea?
Thanks

**Comment by war2973** [comment]
never mind
I've figured it out.

**Comment by ewoutp** [comment]
Same problem here. 
Solved it by creating this file:
```
$ cat /usr/lib/binfmt.d/qemu-aarch64-static.conf
:qemu-aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-aarch64-static:F
```

followed by running:
```
sudo service systemd-binfmt restart
```

**Comment by Jeepgoing** [comment]
hello, could you tell me the reason for this question? @war2973 ，thanks.

**Comment by hougaga** [comment]
How did you slove it?

**Comment by ewoutp** [comment]
Doesn't ring a bell. Sorry

**Comment by MarkZ2012** [comment]
sudo apt purge qemu-user-static
sudo apt install qemu-user-static

This works OK for me on orange pi plus.
