### ISSUE TITLE
Cannot compile Debian release

### ISSUE THREAD

**Issue by Dreddits** [orangepi-xunlong/OrangePi_Build#53]
Compile of release fails...

 Copy qemu emulator binary to rootfs.....
 Copy debian-archive-keyring.....
 Start debootstrap second stage.....
chroot: failed to run command ‘mount’: Exec format error
chroot: failed to run command ‘mount’: Exec format error
chroot: failed to run command ‘/debootstrap/debootstrap’: Exec format error

**Comment by tuxd3v** [comment]
As root:
apt-get install qemu-user-static

Then try Again..
If you found problems building uboot..
Has @leeboby sugested install the libstdc++ 32 bits version:
apt-get install lib32stdc++6

That solved my problem :)

**Comment by orangepi-xunlong** [comment]
You can try the latest Linux SDK, Thanks!
