### ISSUE TITLE
Problem After build Orangepi_Oneplus kernel 4.9

### ISSUE THREAD

**Issue by tuxd3v** [orangepi-xunlong/OrangePi_Build#55]
Hello all,
After  I build up a image, via deboostrap, I noticed that the CPUs are there:

`root@H6:~# cat /proc/cpuinfo 
processor	: 0
BogoMIPS	: 48.00
Features	: fp asimd aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 48.00
Features	: fp asimd aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 48.00
Features	: fp asimd aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 48.00
Features	: fp asimd aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4`

But, I only have one active :(
`root@H6:~# nproc
1`

This is my uname line:
`root@H6:~# uname -a
Linux H6 4.9.118+ #2 SMP PREEMPT Mon Mar 18 01:51:04 WET 2019 aarch64 GNU/Linux`

PAssing Binary generated file to source:
`root@H6:/boot/orangepi# dtc -I dtb -O dts -o OrangePiH6.dtb OrangePiH6.dts
FATAL ERROR: Couldn't open "OrangePiH6.dts": No such file or directory
root@H6:/boot/orangepi# dtc -I dtb -O dts -o OrangePiH6.dts OrangePiH6.dtb
Warning (unit_address_vs_reg): Node /clocks has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc@03000000 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@07022000/s_twi0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@07022000/s_cir0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@07022000/twi_para@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@07022000/pwm16@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@07022000/pwm16@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@07022000/s_uart0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@07022000/s_rsb0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@07022000/s_jtag0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/twi3@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ts0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ts0_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ts1@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ts1_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ts2@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ts2_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ts3@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ts3_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/sdc0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/sdc0@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/sdc1@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/sdc2@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/daudio0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/daudio0_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/daudio2@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/daudio2_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/daudio3@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/daudio3_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spdif@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spdif_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/dmic@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/dmic_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ahub_daudio0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ahub_daudio0_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ahub_daudio2@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ahub_daudio2_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ahub_daudio3@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ahub_daudio3_sleep@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/csi0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/csi_mclk0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/csi_mclk0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/csi_cci0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/scr0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/scr0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/scr0@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/scr1@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/scr1@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/scr1@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/nand0@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/hdmi@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/hdmi@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/hdmi@3 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ac200@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ac200@3 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/gmac@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/card0_boot_para@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/card2_boot_para@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/uart_para@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/jtag_para@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/gmac0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/gmac0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/twi0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/twi0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/twi1@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/twi1@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/twi2@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/twi2@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/twi3@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/uart0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/uart0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/uart1@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/uart1@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/uart2@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/uart2@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/uart3@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/uart3@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spi0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spi0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spi0@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spi0@3 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spi1@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spi1@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spi1@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/spi1@3 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/nand0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/nand0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/lcd0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/lcd0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/hdmi@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ac200@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/ac200@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/pwm0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/pwm0@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/pwm1@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/pwm1@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/csi0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/csi_cci0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/sdc0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/sdc1@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/sdc2@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pinctrl@0300b000/Vdevice@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/standby_space@040020000 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/usbc0@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/usbc1@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/usbc2@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/sound@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/sound@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/sound@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/sound@3 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/sound@4 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/sound@5 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/sound@6 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/spi@05010000/spi_board0 has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc@03000000/lcd0@01c0c000 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/lcd1@01c0c001 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pwm0@0300a000 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pwm1@0300a000 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/spwm0@07020c00 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vind@0/csi@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vind@0/mipi@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vind@0/mipi@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vind@0/scaler@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vind@0/scaler@3 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vind@0/actuator@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vind@0/flash@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vind@0/sensor@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vind@0/sensor@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/vdevice@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pmu@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pmu@0/powerkey@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pmu@0/regulator@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pmu@0/axp_gpio@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/pmu@0/charger@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc@03000000/thermal_sensor has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc@03000000/gpu_cooling has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc@03000000/keyboard has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /n_brom has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /s_brom has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /sram_ctrl has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /sram_a1 has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /sram_a2 has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /prcm has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /s_cpuscfg has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /ion/heap_sys_user@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /ion/heap_sys_contig@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /ion/heap_cma@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /ion/heap_secure@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /dramfreq has a reg or ranges property, but no unit name`

Lots of warnings..
Bellow my Device Tree Source File,
I hadn't touched its configs:

[OrangePiH6.dts.txt](https://github.com/orangepi-xunlong/OrangePi_Build/files/2992930/OrangePiH6.dts.txt)

**Comment by tuxd3v** [comment]
Updating,
Adding dmesg Output..

For what I see it kills CPU 1,2,3

Can any one help?
[dmesg.txt](https://github.com/orangepi-xunlong/OrangePi_Build/files/2992999/dmesg.txt)

Thanks in Advance,
Best Regards

**Comment by orangepi-xunlong** [comment]
It may be helpful to turn off these kernel configurations.  You can try the latest H6 Linux SDK.
```
-CONFIG_CPU_AUTOHOTPLUG=y
-CONFIG_CPU_AUTOHOTPLUG_ROOMAGE=y
-CONFIG_CPU_AUTOHOTPLUG_STATS=y
-CONFIG_CPU_AUTOHOTPLUG_INPUT_EVNT_NOTIFY=y
+# CONFIG_CPU_AUTOHOTPLUG is not set
```

**Comment by tuxd3v** [comment]
hello orangepi-xunlong,
yeah that was the magic bullet :)

Thanks a lot for remind me about that :)

Best Regards,
