### ISSUE TITLE
README is not clear

### ISSUE THREAD

**Issue by albertvanderhorst** [orangepi-xunlong/OrangePi_Build#58]
The readme should make it clear that this source archive is for advanced users and redirect ordinary users to a place where they can just download an image, such as www.orangepi.org then downloads.
Groetjes Albert

**Comment by Thore-Krug** [comment]
I agree

**Comment by yohabi** [comment]
I would add a link into a README.md
http://www.orangepi.org/Docs/Makingabootable.html

It makes the situation more clear - the manual build process is for professionals.

**Comment by albertvanderhorst** [comment]
yohabi schreef op 2019-11-16 19:35:
> I would add a link into a README.md
> http://www.orangepi.org/Docs/Makingabootable.html
> 
> It makes the situation more clear - the manual build process is for
> professionals.
I object to the following text:
"
Welcome to OrangePi Build System! A good place to start in the Linux 
World with OrangePi!

Have fun with your ideas and build your own Linux system.
"

This is just plain ridiculous. It is not a good place to start.
Even an expert like myself can hardly use this site to build a Linux 
system.
A good place to start is armbian.

Having an idea and incorporating it takes months if not years.

Groetjes Albert

-- 
Suffering is the prerogative of the strong, the weak -- perish.
Albert van der Horst

**Comment by orangepi-xunlong** [comment]
Thanks for your advice!

**Comment by albertvanderhorst** [comment]
Orange Pi schreef op 2020-04-07 07:47:
> Closed #58.
I see that you addressed the issue. Nice work!
Groetjes Albert
-- 
Suffering is the prerogative of the strong, the weak -- perish.
Albert van der Horst
