### ISSUE TITLE
Debian Jessie not in distribution

### ISSUE THREAD

**Issue by proguard** [orangepi-xunlong/OrangePi_Build#60]
Hi,
Trying to follow the procedure in the readme to install an image to the OPi one plus. during the 'build release image' process, it cannot find or download the distribution for 'jessie', it then crashes out.
Could this possible be changed to buster.
Alternatively, could you give user the option to type the 'dist' in, and it can get the appropriate one.

Many Thanks
Ayo

**Comment by emi-soft** [comment]
> Hi,
> Trying to follow the procedure in the readme to install an image to the OPi one plus. during the 'build release image' process, it cannot find or download the distribution for 'jessie', it then crashes out.
> Could this possible be changed to buster.
> Alternatively, could you give user the option to type the 'dist' in, and it can get the appropriate one.
> 
> Many Thanks
> Ayo

If still relevant, in the file scripts/00_rootfs_build.sh
change APT_SERVER = mirrors.ustc.edu.cn to APT_SERVER = archive.debian.org

and

 deb https://mirrors.ustc.edu.cn/debian/ $ {release} main contrib non-free
# deb-src https://mirrors.ustc.edu.cn/debian/ $ {release} main contrib non-free
deb https://mrors.ustc.edu.cn/debian/ $ {release} -updates main contrib non-free
# deb-src https://mirrors.ustc.edu.cn/debian/ $ {release} -updates main contrib non-free
deb https://mrors.ustc.edu.cn/debian/ $ {release} -backports main contrib non-free
# deb-src https://mirrors.ustc.edu.cn/debian/ $ {release} -backports main contrib non-free

on

deb http://archive.debian.org/debian/ $ {release} main contrib non-free
# deb-src http://archive.debian.org/debian/ $ {release} main contrib non-free
deb http://archive.debian.org/debian/ $ {release} -updates main contrib non-free
# deb-src http://archive.debian.org/debian/ $ {release} -updates main contrib non-free
deb http://archive.debian.org/debian/ $ {release} -backports main contrib non-free
# deb-src http://archive.debian.org/debian/ $ {release} -backports main contrib non-free

It helped me to collect the image.

**Comment by proguard** [comment]
Thanks
