### ISSUE TITLE
Build ERROR: Run `./create_image` failed

### ISSUE THREAD

**Issue by YunusWang** [orangepi-xunlong/OrangePi_Build#61]
The board is OrangePiZero.  The error is as follows:

Creating root filesistem in local directory linux-xenial...

DEBOOTSTRAP, FIRST STAGE
OK.                        
Creating "sources.list"
Error while loading /bin/bash: No such file or directory
================================================
ERROR on second-stage, instalation NOT FINISHED.
================================================

Is there a solution?

**Comment by HuangXinf** [comment]
because no debootstrap command in create_image, so wget command no execute.
you try:
sudo apt-get install debootstrap

**Comment by orangepi-xunlong** [comment]
Now that you're ready to use the latest code, go back to OrangePi_Build and download OrangePi Zero's Linux SDK.
