### ISSUE TITLE
ath9k driver freezes the network command in RK3399 board

### ISSUE THREAD

**Issue by abhi11796acharya** [orangepi-xunlong/OrangePi_Build#62]
Hi guys,

I want to use a Atheros pci wifi card. I have compiled a new linux image with updated kernel. I had selected ath9k modules for pci cards. But after system reboots network command hangs and I am not able to connect with any network. 

kindly help!

**Comment by orangepi-xunlong** [comment]
We have not tested the pcie wifi module of this model, but only tested that RTL8822BE is available, sorry for that.
