### ISSUE TITLE
android7-h3-bsp

### ISSUE THREAD

**Issue by rradar** [orangepi-xunlong/OrangePi_Build#63]
Hello,

we are badly searching android7-h3-bsp.

Please provide links.

Thank's

**Comment by rradar** [comment]
Basically a source code drop is needed. Please provide. Thank's

**Comment by orangepi-xunlong** [comment]
You can go [www.orangepi.org](http://www.orangepi.org/downloadresources/) to download, android7-h3-bsp has been uploaded to Google network drive.
 

![图片](https://user-images.githubusercontent.com/10287101/70287038-8184f200-1808-11ea-8bb3-9f91f7962880.png)

![图片](https://user-images.githubusercontent.com/10287101/70287184-0a9c2900-1809-11ea-993c-0b74890903aa.png)

**Comment by joek85** [comment]
hello, if you want Android 7.0 source check my repo here
https://github.com/joek85/Android-7.0
it is based on android-7.0.0_r36, if you want to download the image file go to releases. it is made for OPI PLUS 2E, let me know your thoughts.
it includes GAPPS but it is a bit slow, without GAPPS it runs very smoothly.
currently i put it on hold but if you liked it, maybe we can help each other improving it, thank you.
