### ISSUE TITLE
Failed to build on H3 mainline kernel.

### ISSUE THREAD

**Issue by alex-theoto** [orangepi-xunlong/OrangePi_Build#66]
On Debian testing (11) after fixing repository's broken url and set to install the Debian Buster, I got the following error:
`I: Running command: chroot rootfs /debootstrap/debootstrap --second-stage`
`chroot: failed to run command ‘/debootstrap/debootstrap’: Exec format error`
Where is the script for this command? I cannot find with grep.

**Comment by alex-theoto** [comment]
Never mind, somehow this problem solved.

**Comment by 78bash** [comment]
Hello, any idea how this was solved?

**Comment by alex-theoto** [comment]
The problem solved a few days later. I don't know what was wrong, and since I used Debian testing, probably there was something wrong with my compiling programs.
For the time being, problem solved.
