### ISSUE TITLE
ERROR: dragonsecboot  boot_package.cfg failed when build image for OrangePi Zero plus 2 H5

### ISSUE THREAD

**Issue by y-salnikov** [orangepi-xunlong/OrangePi_Build#7]
p=soc c=box_start_os state=0
p=soc c=box_standby_led state=0
p=soc c=gpio_power_key state=0
Conver script to dts ok.
update scp
pack boot package
GetPrivateProfileSection read to end
content_count=3
file /home/jarik/OrangePi/OrangePiH5/output/pack/out/u-boot.fex cant be open
create package failed
ERROR: dragonsecboot  boot_package.cfg failed

**Comment by rmoriz** [comment]
getting the same error

**Comment by orangepi-xunlong** [comment]
Hi, the problem has been solved in the latest code.
