### ISSUE TITLE
调试华为4G模块（me909s-821 miniPcie）时遇到attach又立即断连的问题

### ISSUE THREAD

**Issue by zhouyinwei** [orangepi-xunlong/OrangePi_Build#71]
log如下，烦请协助分析一下，谢谢：
[ 1726.492125] usb 5-1: new high-speed USB device number 11 using xhci-hcd
[ 1726.607951] usb 5-1: New USB device found, idVendor=12d1, idProduct=15c1
[ 1726.607982] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1726.607994] usb 5-1: Product: HUAWEI Mobile V7R11
[ 1726.608005] usb 5-1: Manufacturer: Huawei Technologies Co., Ltd.
[ 1726.608015] usb 5-1: SerialNumber: 0123456789ABCDEF
[ 1726.637866] cdc_ether 5-1:2.0 usb0: register 'cdc_ether' at usb-xhci-hcd.11.auto-1, CDC Ethernet Device, 02:1e:10:1f:00:00
[ 1726.644561] option 5-1:2.2: GSM modem (1-port) converter detected
[ 1726.652448] usb 5-1: GSM modem (1-port) converter now attached to ttyUSB0
[ 1726.654246] option 5-1:2.3: GSM modem (1-port) converter detected
[ 1726.655631] usb 5-1: GSM modem (1-port) converter now attached to ttyUSB1
[ 1726.656976] option 5-1:2.4: GSM modem (1-port) converter detected
[ 1726.658192] usb 5-1: GSM modem (1-port) converter now attached to ttyUSB2
[ 1726.659710] option 5-1:2.5: GSM modem (1-port) converter detected
[ 1726.660959] usb 5-1: GSM modem (1-port) converter now attached to ttyUSB3
[ 1726.663840] option 5-1:2.6: GSM modem (1-port) converter detected
[ 1726.664502] usb 5-1: GSM modem (1-port) converter now attached to ttyUSB4
[ 1727.792947] cdc_ether 5-1:2.0 usb0: unregister 'cdc_ether' usb-xhci-hcd.11.auto-1, CDC Ethernet Device
[ 1727.807168] option1 ttyUSB0: GSM modem (1-port) converter now disconnected from ttyUSB0
[ 1727.807256] option 5-1:2.2: device disconnected
[ 1727.807864] option1 ttyUSB1: GSM modem (1-port) converter now disconnected from ttyUSB1
[ 1727.807942] option 5-1:2.3: device disconnected
[ 1727.808408] option1 ttyUSB2: GSM modem (1-port) converter now disconnected from ttyUSB2
[ 1727.808487] option 5-1:2.4: device disconnected
[ 1727.808943] option1 ttyUSB3: GSM modem (1-port) converter now disconnected from ttyUSB3
[ 1727.809021] option 5-1:2.5: device disconnected
[ 1727.809495] option1 ttyUSB4: GSM modem (1-port) converter now disconnected from ttyUSB4
[ 1727.809574] option 5-1:2.6: device disconnected
[ 1727.947514] cdc_mbim 5-1:3.0: setting rx_max = 16384
[ 1727.947720] cdc_mbim 5-1:3.0: NDP will be placed at end of frame for this device.
[ 1727.948266] cdc_mbim 5-1:3.0: cdc-wdm0: USB WDM device
[ 1727.949442] cdc_mbim 5-1:3.0 wwan0: register 'cdc_mbim' at usb-xhci-hcd.11.auto-1, CDC MBIM, b2:72:4b:52:a0:7a

**Comment by baiywt** [comment]
抱歉，我们没有调试过4G模块。
