### ISSUE TITLE
如何订制开机logo？

### ISSUE THREAD

**Issue by zhouyinwei** [orangepi-xunlong/OrangePi_Build#72]
如何修改开机logo为客户定制化logo？目前默认是OrangePi

**Comment by orangepi-xunlong** [comment]
替换下 [boot.bmp](https://github.com/orangepi-xunlong/external/blob/master/chips/sun50iw6p1/mainline/boot_file/boot.bmp) 即可

在烧好镜像的 TF 卡的 /boot 目录中

**Comment by zhouyinwei** [comment]
烧好镜像的TF卡没办法在windows上打开了，提示需要格式化，如何替换呢？

**Comment by baiywt** [comment]
RK3399的开机logo会打包在boot.img中，只要替换kernel 根目录下的 logo.bmp 和 logo_kernel.bmp这两个文件，重新编译内核，并替换SD卡的内核即可。

**Comment by zhouyinwei** [comment]
> RK3399的开机logo会打包在boot.img中，只要替换kernel 根目录下的 logo.bmp 和 logo_kernel.bmp这两个文件，重新编译内核，并替换SD卡的内核即可。

收到，已经验证成功。默认分辨率是不是1920*1080啊？图片设置成这个分辨率才可以全屏。

**Comment by baiywt** [comment]
是1920*1080。
