### ISSUE TITLE
4G-iot Build

### ISSUE THREAD

**Issue by asefd** [orangepi-xunlong/OrangePi_Build#75]
Hi,
What is the OS distribution and version of Linux that should be used to build the image for 4G-iot?
I tried different distributions of Linux but building never succeeds, I have always different erros.
Thanks

**Comment by baiywt** [comment]
Ubuntu Desktop 18.04(64-bit)

**Comment by asefd** [comment]
Yes finally it passed. I have tested it, but what about modem? Is there any way to make it work on ubuntu or debian?

**Comment by baiywt** [comment]
Modem is not currently supported on Linux, sorry about that.
