### ISSUE TITLE
简化编译---非常建议（可以省去官方很多问题）

### ISSUE THREAD

**Issue by minchieh-fay** [orangepi-xunlong/OrangePi_Build#76]
背景： 我和几个朋友都买了orangepi4， 编译老是各种问题， 而且都报的不一样， 有卡在github的， 有lib32z安装不了的， 有无线网卡编译不过的， 等等等等
大家的编译环境各异，centos7.7， centos6，ubuntu16.04, debian9等等
建议官方， 基于ubuntu, 或者debian, 做个docker镜像，这些官方镜像很小，大概80M的样子：
步骤：
1.yum/apt install docker-ce #安装docker
2.systemctl start docker #启动docker
3.docker pull centos/debian  #拉取centos或debian的官方镜像，centos=200M， debian=80M
4.docker run centos/debian /bin/bash #启动官方镜像， 并进入bash
5.$....  #安装你们编译需要的环境，比如 apt install gcc， 还可以把Orangepi_build放进去， 甚至可以直接把内核等源码放进去
6.docker commit -a “orangepi” -m “xxx” {容器ID}  xunlong/orangepi/build:v1.0.1 # 将镜像报存下来
7. 测试该镜像
8.docker push xunlong/orangepi/build:v1.0.1  #将镜像上传到仓库 

这样大家的编译环境都一样了， 只要官方保证这一个镜像编译没问题， 大家都ok了， 作为我们这些开发者也不用操心这些由自己导致的环境的事了， 何乐不为？ 后面作为生产环境， 批量采用你们板子时， 我们就用你们提供的官方编译镜像 统一出生产包  也挺好的， 是不是？

**Comment by baiywt** [comment]
做了个ubuntu18.04, 可以试一下
sudo apt remove --purge qemu-user-static
sudo apt install qemu-user-static 
sudo docker pull baiywt/orangepi4:v1.0.1
sudo docker run -it --privileged baiywt/orangepi4:v1.0.1 bash
