### ISSUE TITLE
README doesn't list script prerequisites 

### ISSUE THREAD

**Issue by vd-rd** [orangepi-xunlong/OrangePi_Build#77]
The readme should list the package requirements needed to be able to run the script.
For whiptail the newt package should be installed. 
Please update the READme to better reflect this

**Comment by orangepi-xunlong** [comment]
The test environment is Ubuntu18.04, the script will automatically install the relevant dependencies, so please use Ubuntu18.04 to test, if there are still problems, welcome to continue to feedback. Thank you very much!
