### ISSUE TITLE
rootfs compiling error

### ISSUE THREAD

**Issue by luoguangwen** [orangepi-xunlong/OrangePi_Build#81]
OrangePiRK3399/scripts/lib/distributions.sh: line 517: OrangePiRK3399/output/rootfs/etc/network/interfaces.d/eth0: No such file or directory

**Comment by AndreiCherniaev** [comment]
OrangePiRK3399/scripts/lib/distributions.sh contains
ROOTFS="http://cdimage.ubuntu.com/ubuntu-base/releases/${DISTRO}/release/ubuntu-base-18.04-base-${ARCH}.tar.gz"
but this is invalid link. True link is
ROOTFS="http://cdimage.ubuntu.com/ubuntu-base/releases/${DISTRO}/release/ubuntu-base-18.04.5-base-${ARCH}.tar.gz"
