### ISSUE TITLE
执行编译启动脚本 ./build.sh出现问题

### ISSUE THREAD

**Issue by Rainer-king** [orangepi-xunlong/OrangePi_Build#83]
行36: /home/raine/Downloads/OrangePiH3_mainline/scripts/scripts/lib/general.sh: 没有那个文件或目录

**Comment by orangepi-xunlong** [comment]
麻烦详细描述下操作步骤和现象，仅提供这一句log无法判断哪里出问题了

另外请在 Ubuntu 18.04 的 PC 中测试，谢谢！
