### ISSUE TITLE
Orangepizerolts 2.0.8 ubuntu bionic server linux5.4.27 

### ISSUE THREAD

**Issue by fcl989712** [orangepi-xunlong/OrangePi_Build#96]
How does Orangepizerolts 2.0.8 ubuntu bionic server linux5.4.27 Turn on spi function？or its source code

**Comment by orangepi-xunlong** [comment]
1. Add the following configuration in /boot/ orangepiEnv.txt

```
root@orangepizerolts:~# cat /boot/orangepiEnv.txt 
verbosity=1
logo=disabled
console=serial
disp_mode=1920x1080p60
overlay_prefix=sun8i-h3
overlays=usbhost2 usbhost3 spi-spidev
param_spidev_spi_bus=1
```
2. Then reboot

3. You'll see spidev1.0 under /dev after you reboot
