### ISSUE TITLE
运行 Build_OrangePi.sh 失败

### ISSUE THREAD

**Issue by github0null** [orangepi-xunlong/OrangePi_Build#98]
执行脚本时出现：
E: Unable to locate package lib32z1
E: Unable to locate package lib32z1-dev
***
刷新源也没用，用的是 OrangePi Lite ubuntu server 16.04
***
![image](https://user-images.githubusercontent.com/43022536/94990642-45e5c080-05b0-11eb-87e5-9bdc0840894b.png)

**Comment by MarioCavero** [comment]
Did you manage to solve it? How! I tried with:
`sudo dpkg --add-architecture i386`
but when doing `sudo apt update` before installing the libs, I get problems!
